# Generated by Django 3.1.4 on 2021-01-12 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='oink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='feed.oink'),
        ),
    ]
